git:
  depth: 10

compiler: clang

matrix:
  include:
    - os: linux
      env: NODE_VERSION=4.4.7 CXX=g++-5

sudo: false

install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
  - npm install -g npm
  - script/build --create-debian-package --create-rpm-package --compress-artifacts

script: true

cache:
  directories:
    - electron
    - node_modules
    - apm/node_modules
    - script/node_modules
    - ~/.atom/compile-cache

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  artifacts:
    paths:
      - out/atom-amd64.deb
      - out/atom.x86_64.rpm
      - out/atom-amd64.tar.gz
    target_paths: travis-artifacts/$TRAVIS_BUILD_ID
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - fakeroot
    - gcc-multilib
    - gcc-5
    - g++-5
    - git
    - libgnome-keyring-dev
    - rpm
