os:
  - linux
  - osx

install:
  - test "$TRAVIS_OS_NAME" = "linux" && sudo apt-get install build-essential git libgnome-keyring-dev fakeroot || true

script: script/cibuild

notifications:
  email:
    on_success: never
    on_failure: change
