version: "{build}"

skip_tags: true
clone_folder: c:\projects\atom
clone_depth: 10

platform:
  - x86

environment:
  global:
    ATOM_DEV_RESOURCE_PATH: c:\projects\atom
    ATOM_ACCESS_TOKEN:
      secure: Q7vxmSq0bVCLTTRPzXw5ZhPTe7XYhWxX0tQV6neEkddTH6pZkOYNmSCG6VnMX2f+
    ATOM_NOISY_BUILD: 1

  matrix:
  - NODE_VERSION: 4.4.5

install:
  - SET PATH=C:\Program Files\Atom\resources\cli;%PATH%
  - ps: Install-Product node $env:NODE_VERSION $env:PLATFORM
  - npm install -g npm

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - script\bootstrap.cmd
  - script\build.cmd --code-sign --compress-artifacts

test: off
deploy: off
artifacts:
  - path: out\AtomSetup.exe
    name: AtomSetup.exe
  - path: out\AtomSetup.msi
    name: AtomSetup.msi
  - path: out\atom-windows.zip
    name: atom-windows.zip
  - path: out\RELEASES
    name: RELEASES
  - path: out\atom-*-delta.nupkg
    name: atom-delta.nupkg
  - path: out\atom-*-full.nupkg
    name: atom-full.nupkg

cache:
  - '%APPVEYOR_BUILD_FOLDER%\script\node_modules'
  - '%APPVEYOR_BUILD_FOLDER%\apm\node_modules'
  - '%APPVEYOR_BUILD_FOLDER%\node_modules'
  - '%APPVEYOR_BUILD_FOLDER%\electron'
  - '%USERPROFILE%\.atom\.apm'
  - '%USERPROFILE%\.atom\.node-gyp\.atom'
  - '%USERPROFILE%\.atom\.npm'
