trigger:
- 1.* # VSTS only supports wildcards at the end

phases:

- phase: GetReleaseVersion
  steps:
  # This has to be done separately because VSTS inexplicably
  # exits the script block after `npm install` completes.
  - script: |
      cd script\vsts
      npm install
    displayName: npm install
  - script: node script\vsts\get-version.js
    name: Version

# Import OS-specific build definitions
- template: windows.yml
- template: macos.yml
- template: linux.yml
